(define (cube x) (* x x x))

(define (p x) (- (* 3 x) (* 4 (cube x))))

(define (sine radians)
  (if (not (> (abs radians) 0.1))
    radians
    (p (sine (/ radians 3.0)))))

(sine 12.15)

;How many times is the procedure p applied when (sine 12.15) is evaluated
;
; once

;What is the order of growth in space and number of steps
; (as a function of a)
;used by the process generated by the sine procedure when (sine a) is evaluated?
;
; O(log(a))
; 6 steps for 12

(sine 12.15)
(p (sine 4.05))
(p (p (sine 1.3499999999999999)))
(p (p (p (sine .44999999999999996))))
(p (p (p (p (sine .15)))))
(p (p (p (p (p 4.9999999999999996e-2)))))

; 6 steps
